

java_binary(
    name = "jsweet-transpiler",
    srcs = glob(["src/**/*.java"]),
    main_class = "com.github.jsweet_rules.Main",

    deps = [
        "@maven//:org_jsweet_jsweet_transpiler",
        "@maven//:info_picocli_picocli"
    ],
)
