workspace(
    name = "react_webpack",
    managed_directories = {"@npm": ["node_modules"]},
)

### rules_nodejs (https://github.com/bazelbuild/rules_nodejs)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "d14076339deb08e5460c221fae5c5e9605d2ef4848eee1f0c81c9ffdc1ab31c1",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.1/rules_nodejs-1.6.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")

install_bazel_dependencies()

### jvm_external (https://github.com/bazelbuild/rules_jvm_external)

RULES_JVM_EXTERNAL_TAG = "3.0"
RULES_JVM_EXTERNAL_SHA = "62133c125bf4109dfd9d2af64830208356ce4ef8b165a6ef15bbff7460b35c3a"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = "62133c125bf4109dfd9d2af64830208356ce4ef8b165a6ef15bbff7460b35c3a",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "org.jsweet:jsweet-core:6.2.0",
        "io.micronaut:micronaut-runtime:1.3.2",
        "io.micronaut:micronaut-validation:1.3.2",
        "io.micronaut:micronaut-inject:1.3.2",
        "io.micronaut:micronaut-http-client:1.3.2",
        "io.micronaut:micronaut-http-server-netty:1.3.2",
        "ch.qos.logback:logback-classic:1.2.3",
        "javax.annotation:javax.annotation-api:1.3.2"
    ],
    repositories = [
        "https://jcenter.bintray.com",
        "http://repository.jsweet.org/artifactory/libs-release-local/",
        "https://packages.confluent.io/maven",
        "https://repo1.maven.org/maven2/",
    ],
    maven_install_json = "//:maven_install.json"
)

load("@maven//:defs.bzl", "pinned_maven_install")
pinned_maven_install()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_jsweet",
    urls = ["https://github.com/xChrisPx/rules_jsweet/releases/download/0.1.0/rules_jsweet-0.1.0.zip"],
    sha256 = "8bcbbe63e4cd374ef6091d3005e435d76a9d1d4d2af847f8927c2331dfcaa715",
)

load("@rules_jsweet//:repositories.bzl", "rules_jsweet_dependencies")
rules_jsweet_dependencies()
